---
title: "00d_stantroubleshoot"
author: "Wade VanderWright"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Load Packages
library(ape)
library(phytools)
library(nlme)
library(tidyr)
library(ggplot2)
library(dplyr)
library(geiger)
#library(caper)
#library(xlsx)
library(here)
library(readxl)
library(StanHeaders)
library(brms)

library(rstan)
library(gdata)
library(bayesplot)

```

```{r}
stancode = "data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"
```

```{r}
writeLines(stancode,"./test_schools.stan")
```

```{r}
school_test = stan("./test_schools.stan",data=list(J = 8, 
                                                 y = c(28,  8, -3,  7, -1,  1, 18, 12),
                                                 sigma = c(15, 10, 16, 11,  9, 11, 10, 18)))
```

```{r}
school_test
```

```{r}
stancode <- 'data {real y_mean;} parameters {real y;} model {y ~ normal(y_mean,1);}'
out = stan(model_code = stancode,data=list(y_mean=0))

```

```{r}
example(stan_model, package = "rstan", run.dontrun = TRUE)
```


```{r}
#predictor matrix
data_matrix_6 <- model.matrix(~ Log10MeanGSH_centered, data = GSH_df_pgls) #simple one predictor matrix

y <- GSH_df_pgls$Log10CFAR
x <- data_matrix_6
N <- length(GSH_df_pgls$Binomial)
K <- ncol(x)
d_mat <- diag(1, 456, 456)



stan_data6 <- list(N = N, x = x, y = y, K = K, d_mat = d_mat, A = A)


fit6 <- stan(file = './StanModel3.stan', 
             data = stan_data6, 
             warmup = 1000, 
             iter = 5000, 
             chains = 4, 
             cores = 4, 
             thin = 1, 
             pars = c('beta','sigma','lambda', 'log_lik', 'sigma_total'))
```
output:
Error: vector memory exhausted (limit reached?)
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Calls: <Anonymous> ... doTryCatch -> sendData -> sendData.SOCK0node -> serialize
Execution halted
