---
title: "Scrapped BRMS"
author: "Wade VanderWright"
date: '2023-01-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model 3 - GSH ~ PrimaryHabitat
```{r}
brms_3_prior <- get_prior(Log10MeanGSH_centered ~ PrimaryHabitat + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B),
                    family = gaussian())

brms_3 <- brm(Log10MeanGSH_centered ~ PrimaryHabitat + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B), 
                    family = gaussian(),
                    prior = brms_3_prior,
                    warmup = 1000, iter = 5000,
                    cores = 4)

summary(brms_3)
```

```{r}
plot(conditional_effects(brms_3), points = TRUE) #hit enter in the console



```

## Model 4 - GSH ~ Max Depth
```{r}
brms_4_prior <- get_prior(Log10MeanGSH_centered ~ Log10DepthMax_centered + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B),
                    family = gaussian())

#run time was about 30 minutes
brms_4 <- brm(Log10MeanGSH_centered ~ Log10DepthMax_centered + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B),
                    family = gaussian(),
                    prior = brms_4_prior,
                    cores = 4, warmup = 1000,
                    iter = 5000)

summary(brms_4)


```


```{r}
plot(conditional_effects(brms_4), points = TRUE)

```

```{r}
plot(brms_4, N=2, ask = F)
```


## Model 5 - GSH ~ Min Depth
```{r}
brms_5_prior <- get_prior(Log10MeanGSH_centered ~ Log10DepthMin_centered + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B),
                    family = gaussian())

#run time was about 30 minutes
brms_5 <- brm(Log10MeanGSH_centered ~ Log10DepthMin_centered + (1 | gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    data2 = list(B = B),
                    family = gaussian(),
                    prior = brms_5_prior,
                    warmup = 1000, iter = 5000,
                    cores = 4)

summary(brms_5)


```


```{r}
plot(conditional_effects(brms_5), points = TRUE, ask = F)
```

```{r}
plot(brms_5, N=2, ask = F)

```


## Model 7 - GSH ~ Habitat Area
```{r}
brms_7_prior <- get_prior(Log10MeanGSH_centered ~ Log10Area_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_7 <- brm(Log10MeanGSH_centered ~ Log10Area_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_7_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_7)
```

```{r}
plot(conditional_effects(brms_7), points = TRUE, ask = F) 

```

```{r}
plot(brms_7, N=2, ask = F)
```







## Model 8 - CFAR ~ GSH + Max Size + Habitat
```{r}
brms_8_prior <- get_prior(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_8 <- brm(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_8_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_8)
```

```{r}
plot(conditional_effects(brms_8), points = TRUE, ask = F)
```

```{r}
plot(brms_8, N=2, ask = F)
```


```{r}
hyp <- 'sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0'
(hyp <- hypothesis(brms_8, hyp, class = NULL))
plot(hyp)
```

## Model 10 - CFAR ~ GSH + MaxSize + Area
```{r}
brms_10_prior <- get_prior(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered + Log10Area_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_10 <- brm(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered + Log10Area_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_10_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_10)
```

```{r}
plot(conditional_effects(brms_10), points = TRUE, ask = FALSE)

```


## Model 11 - CFAR ~ MaxSize + PrimaryHabitat + Phylogeny
```{r}
brms_11_prior <- get_prior(Log10MeanGSH_centered ~ Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_11 <- brm(Log10MeanGSH_centered ~ Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_11_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_11)
```

```{r}
plot(conditional_effects(brms_11), points = TRUE, ask = F)
```


```{r}
plot(brms_11, points = TRUE, ask = F)
```

```{r}
hyp <- 'sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0'
(hyp <- hypothesis(brms_11, hyp, class = NULL))
plot(hyp)
```

##Model 12 -- GSH ~ CFAR * MaxSize + PrimaryHabitat + Phylogeny
```{r}
BRMS_12_prior <- get_prior(Log10MeanGSH_centered ~ Log10CFAR_centered * Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

BRMS_12_Model <- brm(Log10MeanGSH_centered ~ Log10CFAR_centered * Log10MaxSize_centered + PrimaryHabitat + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = BRMS_12_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(BRMS_12_Model)
```

```{r}
plot(conditional_effects(BRMS_12_Model), points = TRUE, ask = F)
```


```{r}
plot(BRMS_12_Model)

```


##Model 13 -- CFAR ~ GSH * PrimaryHabitat + MaxSize + Phylogeny
```{r}
brms_13_prior <- get_prior(Log10MeanGSH_centered ~ Log10CFAR_centered * Log10MaxSize_centered + Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_13 <- brm(Log10MeanGSH_centered ~ Log10CFAR_centered * Log10MaxSize_centered + Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_13_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_13)
```

```{r}
plot(conditional_effects(brms_13), points = T, ask = F)
```

```{r}
plot(brms_13, points = TRUE, ask = FALSE)
```

## Model 14 - GSH ~ MaxSize + Depth
```{r}
brms_14_prior <- get_prior(Log10MeanGSH_centered ~ Log10MaxSize_centered + Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_14 <- brm(Log10MeanGSH_centered ~ Log10MaxSize_centered + Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_14_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_14)
```


## Model 15 - GSH ~ CFAR + MaxSize * Depth
```{r}
brms_15_prior <- get_prior(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered * Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B))

brms_15 <- brm(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered * Log10DepthMedian_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_pgls,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_14_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_15)
```