---
title: "AnthonyMuseum"
author: "Wade VanderWright"
date: "14/12/2022"
output: html_document
---

## Load packages and data
```{r}
#Load packages
library(here)
library(tidyverse)


##Preload functions
# 'Not in' function
'%nin%' <- Negate('%in%')

# Caudal fin aspect ratio function
caudal_fin <- function(height, area) {
  aspect_ratio <- (height^2 / area)
  return(aspect_ratio)
}

#Centering data function
center_scale <- function(x){
  scale(x, center = mean(x), scale = TRUE)
}
```

```{r}
CalAcad <- read.csv(here('Data', 'Input', 'CalCFAR.csv'), header = T)
#create binomial column
CalAcad <- CalAcad %>% 
  rowwise() %>% 
  mutate(Binomial = paste(LikelyGenus, LikelySpecies, sep = '_'))
#drop NA values from unknown species and specimens without tails
CalAcad <- CalAcad %>% 
  drop_na(Binomial, CFAR)

CalAcad <- CalAcad[-7,]
#fix typos
CalAcad[(CalAcad$Binomial == 'Notorhynchus cepedianus_NA'), "Binomial"] <- 'Notorhynchus_cepedianus'
CalAcad[(CalAcad$Binomial == 'Hexanchus_griseus?'), "Binomial"] <- 'Hexanchus_griseus'


PhysSpec <- CalAcad
PhysSpec[(PhysSpec$Binomial == 'Eusphyrna_blochii'), 'Binomial'] = "Eusphyra_blochii"
PhysSpec[(PhysSpec$Binomial == 'Centrophorus_uyato'), 'Binomial'] = "Centrophorus_uyato" #drop/not in 2013
PhysSpec[(PhysSpec$Binomial == 'Hemipristis_elongatus'), 'Binomial'] = "Hemipristis_elongata"
PhysSpec[(PhysSpec$Binomial == 'Rhizoprionodon_acutis'), 'Binomial'] = "Rhizoprionodon_acutus"
PhysSpec[(PhysSpec$Binomial == 'Heptranchus_perlo'), 'Binomial'] = "Heptranchias_perlo"
PhysSpec[(PhysSpec$Binomial == 'Notorhynchus_cepedianus'), 'Binomial'] = "Notorynchus_cepedianus"
PhysSpec[(PhysSpec$Binomial == 'Carcahrhinus_tjutjot'), 'Binomial'] = "Carcharhinus_tjutjot"
PhysSpec[(PhysSpec$Binomial == 'Paragaleus_randelli'), 'Binomial'] = "Paragaleus_randalli"
PhysSpec[(PhysSpec$Binomial == 'Carcharhinus_cerdale'), 'Binomial'] = "Carcharhinus_cerdale"#drop/not in 2013

PhysSpec <- PhysSpec %>% 
  group_by(Binomial) %>% 
  mutate(Mean_CFAR = mean(CFAR))

PhysSpec <- PhysSpec %>% 
  distinct(Binomial, Mean_CFAR)

Harding <- read.csv(here("Data", "Input", "swimspeed.csv"), header = TRUE)
Harding <- Harding[,c(2,10)]
colnames(Harding) <- c("Binomial","CFAR")
Harding <- Harding[c(6:40,42:46),]
Harding$Binomial <- gsub(" ", "_", Harding$Binomial)
Harding <- Harding %>% 
  distinct(Binomial, CFAR)
Harding_list <- unique(Harding$Binomial)

Harding_summary <- Harding %>% 
  group_by(Binomial) %>% 
  count()

Jacoby <- read.csv(here("Data", "Input", "jacoby.csv"), header = TRUE)
Jacoby <- Jacoby[,c(1,9)]
Jacoby$Species <- str_split(Jacoby$Species, ", ", simplify = TRUE)[,2]
Jacoby$Species <- gsub(" ", "_", Jacoby$Species)
colnames(Jacoby) <- c("Binomial", "CFAR")
Jacoby[9,1] <- "Carcharhinus_obscurus"
Jacoby[15,1] <- "Centrophorus_granulosus"
Jacoby[24,1] <- "Rhincodon_typus"
Jacoby[23,1] <- "Galeocerdo_cuvier"

Jacoby <- Jacoby %>% 
  distinct(Binomial, CFAR)
Jacoby_list <- unique(Jacoby$Binomial)

species_list <- unique(c(Harding_list, Jacoby_list))

swimspeed <- rbind(Harding, Jacoby)
swimspeed$CFAR <- round(as.numeric(swimspeed$CFAR), 2)
swimspeed <- swimspeed %>% 
  distinct(Binomial, CFAR)

Harding_summary <- gt(Harding_summary)
gtsave(Harding_summary, here("Data", "Output", "Harding_summary.png"))

swimspeed <- left_join(swimspeed, PhysSpec, by = "Binomial")
swimspeed <- swimspeed[complete.cases(swimspeed),]

TotalLength_df <- GSH_df %>% 
  filter(Binomial %in% species_list)

TotalLength_df <- TotalLength_df[,c("Binomial","MaxLinearDimension")]

TotalLength_df <- rbind(TotalLength_df, (c("Cetorhinus_maximus", 1973)))

write.csv(file = here("Data","Output","TotalLength.csv"), TotalLength_df)

```


## Regression of physical CFAR ~ book CFAR

do one with an offset of slope of one
do one with the whole museum set


```{r}
cor(swimspeed$Mean_CFAR , swimspeed$CFAR)

model1 <- lm(swimspeed$Mean_CFAR ~ swimspeed$CFAR)
summary(model1)

model2 <- lm()
```

```{r}


pdf(here("Data", "Output", "AnthonyMuseum.p"))

plot(x = swimspeed$CFAR, y = swimspeed$Mean_CFAR, xlab = "", ylab = "")
abline(a = 1.95, b = 0.19, col = "red")
abline(a = 0, b = 1, lty = 2, col = "black")
title(main = paste(c("Correlation", round(cor(swimspeed$Mean_CFAR , swimspeed$CFAR),2))), xlab = "Field Guide CFAR", ylab = "Museum CFAR")

dev.off()
```



```{r}
Plot2 <- ggplot(data = swimspeed, aes(x = CFAR, y = Mean_CFAR, label = Binomial)) +
  geom_abline(intercept = 1.96, slope = 0.19, colour = "red") +
  geom_abline(intercept = 0, slope = 1, lty = 2) + 
  geom_abline(intercept = 0.5, slope = 1, lty = 2) + 
  geom_abline(intercept = -0.5, slope = 1, lty = 2) + 
  geom_point() +
  geom_label_repel(size = 2) +
  annotate("text", x = 1, y = 3.5, label = "cor = 0.29") +
  xlab("swimspeed /Field Guide CFAR") +
  ylab("Museum CFAR") +
  theme_bw() 
  

Plot2

ggsave(here("Data", "Output", "AnthonyMuseumGG.png"), Plot2, height = 5, width = 5)
```

