---
title: "00_DataWrangling"
author: "Wade VanderWright"
date: '2022-03-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###00 -- Data cleaning and wrangling for Ch. 1
## VanderWright, WJ
## May 27, 2022

## Set up
```{r}
##Install packages
#install.packages(c('ape','phytools','nlme','tidyverse','gieger','xlsx','here',
#'readxl','brms','rstan','gdata','bayesplot','StanHeaders', 'caper'))


##Load Packages
library(ape)
library(phytools)
library(nlme)
library(tidyr)
library(tidybayes) #
library(modelr)
library(ggplot2)
library(dplyr)
library(geiger)
#library(caper)
#library(xlsx)
library(here)
library(readxl)
library(StanHeaders)
library(brms)
library(car)
library(rstan)
library(gdata)
library(bayesplot)


##Preload functions
# 'Not in' function
'%nin%' <- Negate('%in%')

# Caudal fin aspect ratio function
caudal_fin <- function(height, area) {
  aspect_ratio <- (height^2 / area)
  return(aspect_ratio)
}

#Centering data function
center_scale <- function(x){
  scale(x, center = mean(x), scale = TRUE)
}

#Run this and skip to line 348
#load(here('./Data/Output/CurrentDataState.RData'))


```

##Load & Clean Data 
```{r}
getwd()

#load last workspace above and skip this ^^^^
#

# SotW GSH Data ####
GSH_df <- read.csv(here('Data', 'Input', 'SharkGillSlitActivity210331 - Sheet1.csv'), header = T)
#drop NAs
GSH_df <- GSH_df %>% drop_na(GS1_proportionTL)
#create binomial
GSH_df <- GSH_df %>% 
  rowwise() %>% 
  mutate(Binomial = paste(Genus, Species, sep = '_'))
#force as character
GSH_df$Binomial <- as.character(GSH_df$Binomial)
#arrange by binomial
GSH_df <- GSH_df %>% 
  arrange(Binomial)
#Calculate the mean GSH per species
GSH_df <- GSH_df %>% 
  rowwise() %>% 
  mutate("MeanGSH" = mean(c(GS1_proportionTL, GS2_proportionTL, GS3_proportionTL, GS4_proportionTL, GS5_proportionTL, GS6_proportionTL, GS7_proportionTL), na.rm = TRUE))
#create Caudal fin aspect ratios and Log10 columns for desired variables 
GSH_df <- GSH_df %>%
  rowwise() %>% 
  mutate("CaudalAspect_proportion_TL" = caudal_fin(TailHeight_proportionTL, TailArea_proportionTL)) %>% 
  mutate(LogMeanGSH = log(MeanGSH)) %>% 
  mutate(LogCFAR = log(CaudalAspect_proportion_TL))
#update taxonomy to match
GSH_df[(GSH_df$Binomial == 'Deania_quadrispinosum'), 'Binomial'] <- 'Deania_quadrispinosa'
GSH_df[(GSH_df$Binomial == 'Ctenacis_fehlmani'), 'Binomial'] <- 'Ctenacis_fehlmanni' 
GSH_df[(GSH_df$Binomial == 'Hemitriakis_leucoperitera'), 'Binomial'] <- 'Hemitriakis_leucoperiptera'
GSH_df[(GSH_df$Binomial == 'Lamiopsis_temmincki'), 'Binomial'] <- 'Lamiopsis_temminckii'
GSH_df[(GSH_df$Binomial == 'Carcharhinus_perezi'), 'Binomial'] <- 'Carcharhinus_perezii'
GSH_df[(GSH_df$Binomial == 'Chiloscyllium_hasselti'), 'Binomial'] <- 'Chiloscyllium_hasseltii'


# Cal Acad GSH and CFAR Data####
#load data
CalAcad <- read.csv(here('Data', 'Input', 'CalCFAR.csv'), header = T)
#create binomial column
CalAcad <- CalAcad %>% 
  rowwise() %>% 
  mutate(Binomial = paste(LikelyGenus, LikelySpecies, sep = '_'))
#drop NA values from unknown species and specimens without tails
CalAcad <- CalAcad %>% 
  drop_na(Binomial, CFAR)

CalAcad <- CalAcad[-7,]
#fix typos
CalAcad[(CalAcad$Binomial == 'Notorhynchus cepedianus_NA'), "Binomial"] <- 'Notorhynchus_cepedianus'
CalAcad[(CalAcad$Binomial == 'Hexanchus_griseus?'), "Binomial"] <- 'Hexanchus_griseus'
#create proportional GSH to compare to drawings
CalAcad <- CalAcad %>% 
  rowwise() %>% 
  mutate(MeanGSH_left = mean(na.omit(c(LGS1, LGS2, LGS3, LGS4, LGS5, LGS6, LGS7))),
         MeanGSH_right = mean(na.omit(c(RGS1, RGS2, RGS3, RGS4, RGS5, RGS6, RGS7))),
         MeanGSH_all = mean(na.omit(c(MeanGSH_left, MeanGSH_right))),
         MeanGSHPropTL = MeanGSH_all/Total_length_cm)


#physical specimens Data from last paper (GSH only)####
VW_2020 <- read.csv(here('Data', 'Input', 'CLEAN_GSH_Data_20190402.csv'), header = T)
#create binomial
VW_2020 <- VW_2020 %>% 
  rowwise() %>% 
  mutate(Binomial = paste(Genus, Species, sep = '_'))
#create mean GSH values
VW_2020 <- VW_2020 %>% 
  group_by(SampleID) %>% 
  mutate(MeanGSH_all = mean(na.omit(c(GillSlitHeightCM_Arch1, GillSlitHeightCM_Arch2,
                                      GillSlitHeightCM_Arch3,GillSlitHeightCM_Arch4,
                                      GillSlitHeightCM_Arch5))),
         MeanGSHPropTL = (MeanGSH_all/TLcm))
#remove duplicates
VW_2020 <- VW_2020 %>% 
  distinct(SampleID, .keep_all = T)
#select and stitch together useful columns
#binomial, MeanGSH_all, MeanGSHPropTL, CFAR
CalAcad <- CalAcad[,c(39,42,43,38)]
#binomial, MeanGSH_all, MeanGSHPropTL
VW_2020 <- VW_2020[,c(17,18,19)]
#fill blank for CFAR
VW_2020$CFAR <- NA
#stitch
PhysSpec <- rbind(CalAcad,VW_2020)

# Depth and habitat Data####
#load data
Habitat <- read_excel(here('./Data/Input/Habitat_species_corrected_210512.xlsx'), sheet = "Current")
#update taxonomy to match
Habitat[(Habitat$Genus_species == 'Carcharhinus_perezi'), 'Genus_species'] <- 'Carcharhinus_perezii'
Habitat[(Habitat$Genus_species == 'Chiloscyllium_hasselti'), 'Genus_species'] <- 'Chiloscyllium_hasseltii'
#filter to match species
Habitat <- Habitat %>% 
  filter(Genus_species %in% GSH_df$Binomial)
#arrange by binomial
Habitat <- Habitat %>% 
  arrange(Genus_species)
#save missing species for later
missing.habitat <- GSH_df[(GSH_df$Binomial %nin% Habitat$Genus_species),]
#trim unused columns from habitat sheet
Habitat <- Habitat[,c(10,22,23,29,31,33,34)]
#join dataframes
GSH_df <- left_join(GSH_df, Habitat, by = c('Binomial' = 'Genus_species'))
GSH_df$MaxLinearDimension <- as.numeric(GSH_df$MaxLinearDimension)
GSH_df$DepthMax_m_text <- as.numeric(GSH_df$DepthMax_m_text)
GSH_df$LogDepthMax <- log(GSH_df$DepthMax_m_text)
GSH_df$DepthMin_m_text <- as.numeric(GSH_df$DepthMin_m_text)
GSH_df$LogDepthMin <- log(GSH_df$DepthMin_m_text)
GSH_df$LogDepthMax[which(GSH_df$LogDepthMax == -Inf)] = 0
GSH_df$LogDepthMin[which(GSH_df$LogDepthMin == -Inf)] = 0

#Log the maximum size column
GSH_df <- GSH_df %>% 
  rowwise() %>% 
  mutate(LogMaxSize = log(MaxLinearDimension),
         MedianDepth_m = mean(c(DepthMin_m_text, DepthMax_m_text)),
         LogDepthMedian = mean(c(LogDepthMax, LogDepthMin)))
#center the Log10 Mean GSH column
GSH_df$LogMeanGSH_centered <- center_scale(GSH_df$LogMeanGSH)
#force numeric
GSH_df$LogMeanGSH_centered <- as.numeric(GSH_df$LogMeanGSH_centered)
#center scale depths
GSH_df$LogDepthMax_centered <- (GSH_df$LogDepthMax - mean(GSH_df$LogDepthMax, na.rm = TRUE)) / sd(GSH_df$Log10DepthMax, na.rm = TRUE)
GSH_df$LogDepthMin_centered <- (GSH_df$LogDepthMin - mean(GSH_df$LogDepthMin, na.rm = TRUE)) / sd(GSH_df$Log10DepthMin, na.rm = TRUE)
GSH_df$LogDepthMedian_centered <- (GSH_df$LogDepthMedian - mean(GSH_df$LogDepthMedian, na.rm = TRUE)) / sd(GSH_df$LogDepthMedian, na.rm = TRUE)

###Phylo Data####
#read in the 10000 trees
FullTree <- read.nexus(here('./Data/Input/10.cal.tree.nex'))
#se the seed for reproduciblility
set.seed(11)
#sample out a tree
SampleFullTree <- sample(FullTree, 1)
SampleFullTree <- SampleFullTree$UNTITLED
#check if tips are binary
is.binary(SampleFullTree)
#check where the tree and dataset differ
namedrops <- name.check(SampleFullTree, GSH_df, GSH_df$Binomial)
#drop the tips that are in the tree and not in the data (all the rays)
SampleFullTree <- drop.tip(SampleFullTree, namedrops$tree_not_data)
#drop the species in the dataset that are not in the tree
GSH_df_full <- subset(GSH_df, GSH_df$Binomial %nin% namedrops$data_not_tree) 

#center the Log10 Max Size column
GSH_df_full$LogMaxSize_centered <- center_scale(GSH_df_full$LogMaxSize)
#force numeric
GSH_df_full$LogMaxSize_centered <- as.numeric(GSH_df_full$LogMaxSize_centered)


#center the Log10 CFAR column
GSH_df_full$LogCFAR_centered <- center_scale(GSH_df_full$LogCFAR)
#force numeric
GSH_df_full$LogCFAR_centered <- as.numeric(GSH_df_full$LogCFAR_centered)

#change habitats to factor
GSH_df_full$PrimaryHabitat <- as.factor(GSH_df_full$PrimaryHabitat)
#add contrast structure
contrasts(GSH_df_full$PrimaryHabitat) = contr.treatment(3)

#order dataframe to match tree tip labels
target <- SampleFullTree$tip.label

GSH_df_full <- GSH_df_full %>% 
  arrange(factor(GSH_df_full$Binomial, levels = target))


#covariance matrix (STAN)
A <- ape::vcv.phylo(SampleFullTree, corr = TRUE)
#(BRMS)
B <- ape::vcv(SampleFullTree, corr = TRUE)


```

## Plot the Tree
```{r}
plot(SampleFullTree, type = 'fan', show.tip=F, edge.color = rainbow(1200))
```

```{r}
###Phylo Data####
#read in the 10000 trees
SeqTree <- read.nexus(here('./Data/Input/output.nex'))
#se the seed for reproduciblility
set.seed(11)
#sample out a tree
SampleSeqTree <- sample(SeqTree, 1)
is.binary(SampleSeqTree)
SampleSeqTree <- SampleSeqTree$tree_0063
#check where the tree and dataset differ
namedrops <- name.check(SampleSeqTree, GSH_df, GSH_df$Binomial)
#drop the tips that are in the tree and not in the data (all the rays)
SampleSeqTree <- drop.tip(SampleSeqTree, namedrops$tree_not_data)
#drop the species in the dataset that are not in the tree
GSH_df_seq <- subset(GSH_df, GSH_df$Binomial %nin% namedrops$data_not_tree) 

#center the Log10 Max Size column
GSH_df_seq$LogMaxSize_centered <- center_scale(GSH_df_seq$LogMaxSize)
#force numeric
GSH_df_seq$LogMaxSize_centered <- as.numeric(GSH_df_seq$LogMaxSize_centered)


#center the Log10 CFAR column
GSH_df_seq$LogCFAR_centered <- center_scale(GSH_df_seq$LogCFAR)
#force numeric
GSH_df_seq$LogCFAR_centered <- as.numeric(GSH_df_seq$LogCFAR_centered)

#change habitats to factor
GSH_df_seq$PrimaryHabitat <- as.factor(GSH_df_seq$PrimaryHabitat)
#add contrast structure
contrasts(GSH_df_seq$PrimaryHabitat) = contr.treatment(3)

#order dataframe to match tree tip labels
target <- SampleSeqTree$tip.label

GSH_df_seq <- GSH_df_seq %>% 
  arrange(factor(GSH_df_seq$Binomial, levels = target))


#covariance matrix (STAN)
C <- ape::vcv.phylo(SampleSeqTree, corr = TRUE)
#(BRMS)
D <- ape::vcv(SampleSeqTree, corr = TRUE)


```

## Plot the Tree
```{r}
plot(SampleSeqTree, type = 'fan', show.tip=F, edge.color = rainbow(700))
```