---
title: "00d_stantroubleshoot"
author: "Wade VanderWright"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
stancode = "data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"
```

```{r}
writeLines(stancode,"./test_schools.stan")
```

```{r}
school_test = stan("./test_schools.stan",data=list(J = 8, 
                                                 y = c(28,  8, -3,  7, -1,  1, 18, 12),
                                                 sigma = c(15, 10, 16, 11,  9, 11, 10, 18)))
```

```{r}
school_test
```

```{r}
stancode <- 'data {real y_mean;} parameters {real y;} model {y ~ normal(y_mean,1);}'
out = stan(model_code = stancode,data=list(y_mean=0))

```

```{r}
example(stan_model, package = "rstan", run.dontrun = TRUE)
```

