---
title: "01a_PhysicalSpecimens"
author: "Wade VanderWright"
date: '2022-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 01a_PhysicalSpecimens - Comparison of physical specimens to field guide illustations
## VanderWright, WJ
## June 20, 2022

#Fix binomial issues
```{r}
fix_list <- PhysSpec[which(PhysSpec$Binomial %nin% GSH_df_pgls$Binomial),]
fix_list <- fix_list %>% 
  distinct(Binomial, .keep_all = T)

PhysSpec[(PhysSpec$Binomial == 'Eusphyrna_blochii'), 'Binomial'] = "Eusphyra_blochii"
PhysSpec[(PhysSpec$Binomial == 'Centrophorus_uyato'), 'Binomial'] = "Centrophorus_uyato" #drop/not in 2013
PhysSpec[(PhysSpec$Binomial == 'Hemipristis_elongatus'), 'Binomial'] = "Hemipristis_elongata"
PhysSpec[(PhysSpec$Binomial == 'Rhizoprionodon_acutis'), 'Binomial'] = "Rhizoprionodon_acutus"
PhysSpec[(PhysSpec$Binomial == 'Heptranchus_perlo'), 'Binomial'] = "Heptranchias_perlo"
PhysSpec[(PhysSpec$Binomial == 'Notorhynchus_cepedianus'), 'Binomial'] = "Notorynchus_cepedianus"
PhysSpec[(PhysSpec$Binomial == 'Carcahrhinus_tjutjot'), 'Binomial'] = "Carcharhinus_tjutjot"
PhysSpec[(PhysSpec$Binomial == 'Paragaleus_randelli'), 'Binomial'] = "Paragaleus_randalli"
PhysSpec[(PhysSpec$Binomial == 'Carcharhinus_cerdale'), 'Binomial'] = "Carcharhinus_cerdale"#drop/not in 2013


fix_list <- PhysSpec[which(PhysSpec$Binomial %nin% GSH_df_pgls$Binomial),]

PhysSpec <- PhysSpec[which(PhysSpec$Binomial %nin% fix_list$Binomial),]

```



#Create species distribution for samples >1
```{r}
# count samples per species
PhysSpec_count <- PhysSpec %>% 
  count(Binomial)
#filter count by species with more than 1 sample
PhysSpec_count <- PhysSpec_count %>% 
  filter(n > 1)
#make a multiple sample list
PhysSpec_mutli <- subset(PhysSpec, PhysSpec$Binomial %in% PhysSpec_count$Binomial)
#make a single sample list
PhysSpec_singles <- subset(PhysSpec, PhysSpec$Binomial %nin% PhysSpec_count$Binomial)
# bootstrapping 
# function to bootstrap (simulate) mean gill slit height proportions for each species

bs_func <- function(x){
  # new dataframe for each species
    newdat <- PhysSpec_mutli %>% filter(., Binomial == x)
  
  # set seed so repeatable
    set.seed(8) # go giants!
  
  # create a new dataframe with the Species' name and simulated GSH proportion data
  
    # generate new GSH proportion values drawn from a normal distribution with a mean and sd of each species GSH proportions
    y <- rnorm(100, mean(newdat$MeanGSHPropTL), sd(newdat$MeanGSHPropTL))

    # generate column of species name
    x <- rep(x, 100)
    
    #Generate new CFAR proportion values based on normal distribution of samples
    tmp <- replace(newdat, is.na(newdat), 0) #doesn't this drag down the mean?
    z <- rnorm(100, mean(tmp$CFAR), sd(tmp$CFAR))
    
    # merge
    df <- data.frame(x,y,z)

}

# generate a vector of species names to apply the function to
sp_list <- unique(PhysSpec_mutli$Binomial)

# apply the function and create a new list of the output
bs_values <- lapply(sp_list, bs_func)

# turn the list into a dataframe
bs_val <- bind_rows(bs_values) %>%
          rename(Binomial = x,
                 MeanGSHPropTL = y,
                 CFAR = z)
#remove**
bs_val_CI <- bs_val %>%
             group_by(Binomial) %>%
             dplyr::summarise(., quantile(MeanGSHPropTL, probs = c(0.025, 0.5, 0.975), na.rm = T),
                              ., quantile(CFAR, probs = c(0.025, 0.5, 0.975), na.rm = T))


GSH_quantile_func <- function(x){
  # new dataframe for each species
    newdat <- bs_val %>% filter(., Binomial == x)
    
    CI_GSH <- quantile(newdat$MeanGSHPropTL, probs = c(0.025,0.5, 0.975), na.rm = T)

    CI_GSH
}
 
CFAR_quantile_func <- function(x){
  newdat <- bs_val %>% filter(., Binomial == x)
  
  CI_CFAR <- quantile(newdat$CFAR, probs = c(0.025, 0.5, 0.975), na.rm=T)
  
  CI_CFAR
}
  
GSH_CI_species <- sapply(sp_list, GSH_quantile_func)

CFAR_CI_species <- sapply(sp_list, CFAR_quantile_func)


gather.matrix <- function(mat) {
  if (is.null(dimnames(mat))) {
    grid <- expand.grid(seq.int(nrow(mat)), seq.int(ncol(mat)))
  } else {
    grid <- expand.grid(dimnames(mat))
  }
  cbind(grid, value = as.vector(mat))
}

GSH_CI_species <- gather.matrix(GSH_CI_species)

CFAR_CI_species <- gather.matrix(CFAR_CI_species)

CI_species <- left_join(GSH_CI_species, CFAR_CI_species, by = c("Var2", "Var1"))

CI_species <- CI_species %>% mutate(value.y = if_else(value.y < 0, 0, value.y))

write.csv(CI_species, file = here("./Data/Output/CalAcad_Physical_CIs.csv"))
```

#Create average CI from above
```{r}
CI_species <- CI_species %>% 
  group_by(Var2) %>% 
  mutate(GSH_CI_range = max(value.x) - min(value.x),
         CFAR_CI_range = max(value.y) - min(value.y))

GSH_CI_max <- max(CI_species$GSH_CI_range)
GSH_CI_min <- min(CI_species$GSH_CI_range)
GSH_CI_average <- mean(CI_species$GSH_CI_range)

CFAR_CI_max <- max(CI_species$CFAR_CI_range, na.rm = T)
CFAR_CI_min <- min(CI_species$CFAR_CI_range, na.rm = T)
CFAR_CI_average <- mean(CI_species$CFAR_CI_range, na.rm = T)

```

#Create single specimen species with average CI
```{r}
PhysSpec_singles <- PhysSpec_singles %>% 
  rowwise() %>% 
  mutate(MeanGSHPropTL_upperCI = MeanGSHPropTL + (0.5*GSH_CI_average),
         MeanGSHPropTL_lowerCI = MeanGSHPropTL - (0.5*GSH_CI_average),
         CFAR_upperCI = CFAR + (0.5*CFAR_CI_average),
         CFAR_lowerCI = CFAR - (0.5*CFAR_CI_average))

PhysSpec_singles <- PhysSpec_singles %>% mutate(CFAR_lowerCI = if_else(CFAR_lowerCI < 0, 0, CFAR_lowerCI))


```

#Get list of species from field guide that match physical specimens
```{r}

SotW <- GSH_df_pgls %>% 
  filter(Binomial %in% PhysSpec$Binomial) 

```
#Left join SotW data to physical specimens
```{r}
#left join for multiples with CI
colnames(CI_species) <- c('Var1','Binomial','value.x','value.y','GSH_CI_range', 'CFAR_CI_range')

SotW_multi <- SotW %>% 
  filter(Binomial %in% CI_species$Binomial) %>% 
  select(Binomial, MeanGSH, CaudalAspect_proportion_TL)

PhysSpec_mutli <- left_join(CI_species, SotW_multi, by = "Binomial" )
#left join for singles
SotW_singles <- SotW %>% 
  filter(Binomial %in% PhysSpec_singles$Binomial) %>% 
  select(Binomial, MeanGSH, CaudalAspect_proportion_TL)

PhysSpec_singles <- left_join(PhysSpec_singles, SotW_singles, by = "Binomial")

```
