---
title: "01a_PGLS"
author: "Wade VanderWright"
date: '2022-03-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###01_a -- PGLS Models for Ch. 1
## VanderWright, WJ
## March 16, 2022


#Model 5 - CFAR ~ GSH + tree

```{r}
pglsMod1 <- gls(Log10CFAR ~ Log10MeanGSH_centered, 
                correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), 
                data = GSH_df_pgls, method = "ML")

summary(pglsMod1)

```

```{r}
plot(Log10CFAR ~ Log10MeanGSH_centered, data = GSH_df_pgls, pch=20)
abline(a = coef(pglsMod1)[1], b = coef(pglsMod1)[2], col = 6, lw = 2)
abline(a = confint(pglsMod1)[1,1], b = confint(pglsMod1)[2,1], col = 'blue', lw = 1)
abline(a = confint(pglsMod1)[1,1], b = confint(pglsMod1)[2,2], col = 'red', lw = 1)
abline(a = confint(pglsMod1)[1,2], b = confint(pglsMod1)[2,1], col = 'blue', lw = 1)
abline(a = confint(pglsMod1)[1,2], b = confint(pglsMod1)[2,2], col = 'red', lw = 1)

```


#Model 6 - CFAR ~ GSH * MaxSize + tree
```{r}
pglsMod2 <- gls(Log10CFAR ~ Log10MeanGSH_centered * Log10MaxSize_centered, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod2)
```

```{r}
plot(Log10CFAR ~ Log10MeanGSH_centered, data = GSH_df_pgls, pch = 20)

abline(a = coef(pglsMod2)[1], b = coef(pglsMod2)[2], col = 6, lw = 2)
```
#Model 7 - CFAR ~ GSH + MaxSize + tree
```{r}
pglsMod3 <- gls(Log10CFAR ~ Log10MeanGSH_centered + Log10MaxSize_centered, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod3)
```

```{r}
plot(Log10CFAR ~ Log10MeanGSH_centered, data = GSH_df_pgls, pch = 20)

abline(a = coef(pglsMod3)[1], b = coef(pglsMod3)[2], col = 6, lw = 2)
```
#Model 8 - CFAR ~ GSH + PrimaryHabitat + tree
```{r}
pglsMod5 <- gls(Log10CFAR ~ Log10MeanGSH_centered + PrimaryHabitat, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod5)
```

```{r}
plot(Log10CFAR ~ Log10MeanGSH_centered, data = GSH_df_pgls, pch = 20)

abline(a = coef(pglsMod5)[1], 
       b = coef(pglsMod5)[2], 
       col = 6, lw = 2)

abline(a = coef(pglsMod5)[1] + coef(pglsMod5)[3], 
       b = coef(pglsMod5)[2], col = 'blue', lw =2)
       
abline(a = (coef(pglsMod5)[1] + coef(pglsMod5)[4]), 
       b = coef(pglsMod5)[2], 
       col = 'green', lw =2)

```

#Model 9 - CFAR ~ GSH * PrimaryHabitat + tree
```{r}
pglsMod6 <- gls(Log10CFAR ~ Log10MeanGSH_centered * PrimaryHabitat, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod6)
```

```{r}
plot(Log10CFAR ~ Log10MeanGSH_centered, data = GSH_df_pgls, pch = 20)
#coastal (a = 1, b = 2)
abline(a = coef(pglsMod6)[1], 
       b = coef(pglsMod6)[2], 
       col = 6, lw = 2)
#deepwater (a = 1 + 3, b = 2 + 5)
abline(a = coef(pglsMod6)[1] + coef(pglsMod6)[3], 
       b = coef(pglsMod6)[2] + coef(pglsMod6)[5], 
       col = 'blue', lw =2)
#pelagic (a = 1 + 4, b = 2 + 6)       
abline(a = (coef(pglsMod6)[1] + coef(pglsMod6)[4]), 
       b = (coef(pglsMod6)[2] + coef(pglsMod6)[6]), 
       col = 'green', lw =2)

```







#Model 11 - CFAR ~ GSH * MaxSize + PrimaryHabitat + tree
```{r}
pglsMod8 <- gls(Log10CFAR ~ Log10MeanGSH_centered * Log10MaxSize_centered + PrimaryHabitat, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod8)
```

#Model 12 - CFAR ~ GSH + MaxSize + PrimaryHabitat + tree
```{r}
pglsMod7 <- gls(Log10CFAR ~ Log10MeanGSH_centered + Log10MaxSize_centered + PrimaryHabitat, correlation = corPagel(phy = SampleTree, value = 0.5, fixed = F, form = ~Binomial), data = GSH_df_pgls, method = "ML")

summary(pglsMod7)
```



