---
title: "01b_BRMS_2"
author: "Wade VanderWright"
date: '2023-04-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#01_b -- BRMS Models for Ch. 1 (sequenced tree)
## VanderWright, WJ
## April 11, 2023
## Updated: NA


## Model 1 - GSH ~ CFAR

```{r}
brms_5_prior <- get_prior(LogMeanGSH_centered ~ LogCFAR_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    data2 = list(D = D),
                    family = gaussian())


brms_5 <- brm(LogMeanGSH_centered ~ LogCFAR_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    data2 = list(D = D),
                    family = gaussian(),
                    prior = brms_5_prior,
                    warmup = 1000, iter = 5000,
                    cores = 4
                    )

summary(brms_5)
```

```{r}
plot(conditional_effects(brms_5), points = TRUE)

```

```{r}
plot(brms_5, N=2, ask = F)

```


```{r}
#lamda estimate
hyp <- "sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0"
(hyp <- hypothesis(brms_5, hyp, class = NULL))
```


```{r}
plot(hyp)
```

## Model 2 - GSH ~ Max Size
```{r}
brms_6_prior <- get_prior(LogMeanGSH_centered ~ LogMaxSize_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    data2 = list(D = D),
                    family = gaussian())

brms_6 <- brm(LogMeanGSH_centered ~ LogMaxSize_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    data2 = list(D = D),
                    family = gaussian(),
                    prior = brms_6_prior,
                    warmup = 1000, iter = 5000,
                    cores = 4
                    )

summary(brms_6)

```


```{r}
plot(conditional_effects(brms_6), points = TRUE) #hit enter in the console

```

```{r}
plot(brms_6, N=2, ask = F)

```


```{r}
#lamda estimate
hyp <- "sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0"
(hyp <- hypothesis(brms_6, hyp, class = NULL))
```
```{r}
plot(hyp)
```


## Model 3 - GSH ~ Median Depth 
```{r}
brms_7_prior <- get_prior(LogMeanGSH_centered ~ LogDepthMedian_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    family = gaussian(),
                    data2 = list(D = D))

#run time was about 30 minutes
brms_7 <- brm(LogMeanGSH_centered ~ LogDepthMedian_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    family = gaussian(),
                    data2 = list(D = D),
                    prior = brms_7_prior,
                    cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_7)


```


```{r}
plot(conditional_effects(brms_7), points = TRUE)

```

```{r}
plot(brms_7, N=2, ask = F)

```


```{r}
#lamda estimate
hyp <- "sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0"
(hyp <- hypothesis(brms_7, hyp, class = NULL))
```

```{r}
plot(hyp)
```


## Model 4 - CFAR ~ GSH + MaxSize + Median Depth
```{r}
brms_8_prior <- get_prior(LogMeanGSH_centered ~ LogCFAR_centered + LogMaxSize_centered + LogDepthMedian_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    family = gaussian(),
                    data2 = list(D = D))

brms_8 <- brm(LogMeanGSH_centered ~ LogCFAR_centered + LogMaxSize_centered + LogDepthMedian_centered + (1|gr(Binomial, cov = D)),
                    data = GSH_df_seq,
                    family = gaussian(),
                    data2 = list(D = D),
                    prior = brms_4_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)

summary(brms_8)
```

```{r}
conditions <- data.frame(LogDepthMedian_centered = c(-1, 0, 1))
plot(conditional_effects(brms_8, effects = "LogCFAR_centered",
                         conditions = conditions,  spaghetti = TRUE, ndraws = 1000), points = TRUE)
```

```{r}
#lamda estimate
hyp <- "sd_Binomial__Intercept^2 / (sd_Binomial__Intercept^2 + sigma^2) = 0"
(hyp <- hypothesis(brms_8, hyp, class = NULL))
plot(hyp)
```


```{r}
pp_check(brms_8)
```

```{r}
plot(conditional_effects(brms_8), points = TRUE, ask = FALSE)
```
## R2 vals
```{r}
bayes_R2(brms_5)
```

```{r}
bayes_R2(brms_6)
```

```{r}
bayes_R2(brms_7)
```

```{r}
bayes_R2(brms_8)
```

## pp checks

```{r}
pp_check(brms_5, ndraws = 150)
```

```{r}
pp_check(brms_6, ndraws = 150)
```

```{r}
pp_check(brms_7, ndraws = 150)
```

```{r}
pp_check(brms_8, ndraws = 150)
```





##LOO comapre (quick and dirty version)

```{r}
fit5_loo <- loo(brms_5)
fit6_loo <- loo(brms_6)
fit7_loo <- loo(brms_7)
fit8_loo <- loo(brms_8)


brms_loo_phylo_list <- list(fit5_loo, fit6_loo, fit7_loo, fit8_loo)
brms_loo_phylo_seq <- loo_compare(brms_loo_phylo_list)
loo_model_weights_2(brms_loo_phylo_list)

LOO_Table_2 <- data.frame(round(brms_loo_phylo_seq, 2))

write.csv(LOO_Table_2, file = here("./Data/Output/LOO_Table_2.csv"), row.names = T)

brms_loo_phylo_seq
```

## Summary of models
```{r}
tbl1_title <- data.frame("Model 1 - Activity",NA,NA,NA)
names(tbl1_title) <- names(Table_1)
Table_1 <- data.frame(round(fixef(brms_5, summary = TRUE), 2))
tbl2_title <- data.frame("Model 2 - Size",NA,NA,NA)
names(tbl2_title) <- names(Table_1)
Table_2 <- data.frame(round(fixef(brms_6, summary = TRUE), 2))
tbl3_title <- data.frame("Model 3 - Depth",NA,NA,NA)
names(tbl3_title) <- names(Table_1)
Table_3 <- data.frame(round(fixef(brms_7, summary = TRUE), 2))
tbl4_title <- data.frame("Model 4 - Ecological lifestyle",NA,NA,NA)
names(tbl4_title) <- names(Table_1)
Table_4 <- data.frame(round(fixef(brms_8, summary = TRUE), 2))


Table_5 <- rbind(tbl1_title,Table_1,
                 tbl2_title,Table_2,
                 tbl3_title,Table_3,
                 tbl4_title,Table_4)

write.csv(Table_5, file = here("./Data/Output/Model_summaries_seq_230412.csv"))
Table_5
```

### VIF check
```{r}
library(car)

linear_mod <- lm(Log10MeanGSH_centered ~ Log10CFAR_centered + Log10MaxSize_centered + Log10DepthMedian_centered, data = GSH_df_seq)

vif(linear_mod)
```

```{r}
data <- GSH_df_seq[,c("LogMeanGSH_centered", "LogCFAR_centered", "LogMaxSize_centered", "LogDepthMedian_centered")]

cor(data)
```



### Save the environment
```{r}
save.image(here('./Data/Output/CurrentDataState.RData'))


saveRDS(brms_5, here("Data", "Output", "brms_1.rds"))
saveRDS(brms_6, here("Data", "Output", "brms_2.rds"))
saveRDS(brms_7, here("Data", "Output", "brms_3.rds"))
saveRDS(brms_8, here("Data", "Output", "brms_4.rds"))
```


