---
title: "Diagnostics"
author: "Wade VanderWright"
date: '2022-03-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Physical specimen Plots
##Multi specimen plot
```{r}
#create new df for plotting
library(forcats)

df <- as_tibble(PhysSpec_mutli)
df <- df[,c(2:ncol(df))]
df$Binomial <- str_replace(df$Binomial, "_", " ")

#GSH plot
P1 <- df %>% 
  mutate(Binomial = fct_reorder(Binomial, desc(MeanGSH), .fun = 'median')) %>% 
  ggplot(aes(x = Binomial, y =  value.x)) +
  geom_boxplot() +
  geom_point(aes(x = Binomial, y = MeanGSH), data = df, color = 'red') +
  ylim(0.0,0.11) +
  theme_light() +
  annotate("text", x = 30, y = 0.08, label = "16/32 = 50%") +
    coord_flip() +
  xlab("Species") +
theme(axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.text.y = element_text(face = 'italic'),
      panel.grid = element_blank())


P1

16/32

#CFAR plot

P2 <- df %>% 
  mutate(Binomial = fct_reorder(Binomial, desc(MeanGSH), .fun = 'median')) %>% 
  ggplot(aes(x = Binomial, y = value.y, drop = TRUE)) +
  geom_boxplot() +
  geom_point(aes(x = Binomial, y = CaudalAspect_proportion_TL), data = df, color = 'red') +
  ylim(0,8) +
  ylab("CFAR") +
  xlab("Species") +
  annotate("text", x = 30, y = 6, label = "26/29 = 90%") +
      coord_flip() +
  theme_light() +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        panel.grid = element_blank())

P2

#26/29 *
  


library(patchwork)

P_multi <- P1 | P2
P_multi
```

##Single specimen plot
```{r}
df2 <- as_tibble(PhysSpec_singles)
df2$Binomial <- str_replace(df2$Binomial, "_", " ")

#GSH plot
P3 <- df2 %>% 
  mutate(Binomial = fct_reorder(Binomial, desc(MeanGSH))) %>% 
  ggplot(aes(x = Binomial, y = MeanGSHPropTL)) +
  geom_segment(aes(xend = Binomial, y = MeanGSHPropTL_upperCI, yend = MeanGSHPropTL_lowerCI), lineend = "butt", color = 'grey', size = 2) +
  geom_segment(aes(xend = Binomial, y = MeanGSHPropTL_maxCI, yend = MeanGSHPropTL_minCI), 
               lineend = "butt", color = 'grey') +
  geom_point() +
  geom_point(aes(x = Binomial, y = MeanGSH), data = df2, color = 'red') +
  ylim(0.0,0.11) +
  ylab("Mean Gill Slit Height") +
  xlab("Species") +
  annotate("text", x = 16, y = 0.08, label = "12/17 = 71%") +
  coord_flip() +
  theme_light() +
  theme(#axis.text.x = element_blank(),
        axis.text.y = element_text(face = 'italic'),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        panel.grid = element_blank()) 
P3

#10/17

#CFAR plot

P4 <- df2 %>% 
  mutate(Binomial = fct_reorder(Binomial, desc(MeanGSH))) %>%
  ggplot(aes(x = Binomial, y = CFAR, drop = TRUE)) +
  geom_segment(aes(xend = Binomial, y = CFAR_upperCI, yend = CFAR_lowerCI), lineend = "butt", color = 'grey', size = 2) +
  geom_segment(aes(xend = Binomial, y = CFAR_maxCI, yend = CFAR_minCI), lineend = "butt", color = 'grey') +
  geom_point() +
  geom_point(aes(x = Binomial, y = CaudalAspect_proportion_TL), data = df2, color = 'red') +
  ylim(0,8) +
  xlab("Species") +
  annotate("text", x = 16, y = 6, label = "17/17 = 100%") +
  coord_flip() +
  theme_light() +
  theme(axis.text.y = element_blank(),
        #axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank())

P4


P_singles <- P3 | P4
P_singles
```

##Stitch them together
```{r}
Fig1 <- P_multi / P_singles +
  plot_annotation(tag_levels = 'A')
Fig1


png(here('./Data/Output/Figure1_PhysicalSpecimens_draft.png'), width = 20, height = 30,
    units = "cm", res = 800, bg = "transparent")

Fig1

dev.off()
```


#PCA Plots


#BRMS output plots
```{r}


color_scheme_set("mix-blue-pink")
p <- mcmc_trace(brms_11, pars = c("b_Intercept","b_Log10MeanGSH_centered","b_Log10MaxSize_centered","b_PrimaryHabitat2",                                      
                                  "b_PrimaryHabitat3","b_Log10MeanGSH_centered:Log10MaxSize_centered","sd_Binomial__Intercept",
                                  "sigma"), n_warmup = 1000,
                facet_args = list(nrow = 2, labeller = label_parsed))
p + facet_text(size = 15)
```

```{r}
posterior11_c <- as.matrix(brms_11)
color_scheme_set('purple')

dimnames(posterior11_c)[[2]] <- c("alpha", "beta", "MaxSize", "Deepwater", "Pelagic", "GSH:MaxSize", "sigma", "lambda", "log_lik", "lp__") 


mcmcareaplot <- mcmc_areas(posterior11_c, pars = c("alpha", "beta", "sigma", "lambda"), prob = 0.95)
 ggsave(here('./Data/Output/MCMC_Area_plot1.pdf'), mcmcareaplot, device = 'pdf', height = 6, width = 8, units = 'in')

mcmcareaplot <- mcmcareaplot +
  theme_transparent()

png(here('./Data/Output/MCMC_Area_plot2.png'), width = 20, height = 15,
    units = "cm", res = 800, bg = "transparent")

mcmcareaplot

dev.off()
 
```

```{r}
color_scheme_set("brightblue")
brms_9 %>%
  posterior_predict(draws = 500) %>%
  ppc_stat(y = GSH_df_pgls$Log10MeanGSH_centered,
                   stat = "mean")
```

```{r}

###bae plot###
color_scheme_set('brightblue')
bayesplot_theme_set(theme_transparent())

PPC_plot1 <- ppc_intervals(
  y = GSH_df_pgls$Log10CFAR,
  yrep = posterior_predict(brms_11),
  x = as.numeric(GSH_df_pgls$Log10MeanGSH_centered),
  prob = 0.5, prob_outer = 0.95
) +
  labs(
    x = "Log10 Mean GSH",
    y = "Log10 CFAR",
    title = "95% posterior predictive intervals \nvs observed CFAR",
  ) 



### coastal ranges###
coastal_spp <- GSH_df_pgls %>% 
  filter(PrimaryHabitat == 'Coastal') %>% 
  arrange(Log10MeanGSH_centered)

coastal_spp_range <- c(as.numeric(coastal_spp[1,36]), as.numeric(coastal_spp[198,36]), as.numeric(coastal_spp[1,37]), as.numeric(coastal_spp[198,37]))

coastal_ystart = coastal_spp_range[1]*fit11_summary[2,1] + #GSH slope
                 coastal_spp_range[3]*fit11_summary[3,1] + #Size slope
                 fit11_summary[6,1]*coastal_spp_range[1]*coastal_spp_range[3] + #interaction 
                 fit11_summary[1,1] #intercept
  
coastal_yend = coastal_spp_range[2]*fit11_summary[2,1] + 
               coastal_spp_range[4]*fit11_summary[3,1] + 
               fit11_summary[6,1]*coastal_spp_range[2]*coastal_spp_range[4] + 
               fit11_summary[1,1]

PPCplot1 <- PPC_plot1 + geom_abline(intercept = fit11_summary[1,1], slope = fit11_summary[2,1] )

PPC_plot1 <- PPC_plot1 + geom_segment(x = coastal_spp_range[1], xend = coastal_spp_range[2], y = coastal_ystart, yend = coastal_yend, color = 'orange')

###deepwater###
deepwater_spp <- GSH_df_pgls %>% 
  filter(PrimaryHabitat == 'Deepwater') %>% 
  arrange(Log10MeanGSH_centered)

deepwater_spp_range <- c(as.numeric(deepwater_spp[1,36]), as.numeric(deepwater_spp[232,36]), as.numeric(deepwater_spp[1,37]), as.numeric(deepwater_spp[232,37]))

deepwater_ystart = deepwater_spp_range[1]*fit11_summary[2,1] + 
  deepwater_spp_range[3]*fit11_summary[3,1] + 
  fit11_summary[4,1]*deepwater_spp_range[1] + 
  fit11_summary[6,1]*deepwater_spp_range[1]*deepwater_spp_range[3] + 
  fit11_summary[1,1]
  
deepwater_yend = deepwater_spp_range[2]*fit11_summary[2,1] + deepwater_spp_range[4]*fit11_summary[3,1] + fit11_summary[6,1]*deepwater_spp_range[2]*deepwater_spp_range[4] + fit11_summary[1,1]


PPC_plot1 <- PPC_plot1 + geom_segment(x = deepwater_spp_range[1], xend = deepwater_spp_range[2], y = deepwater_ystart, yend = deepwater_yend, color = 'green')
PPC_plot1

###pelagic###
pelagic_spp <- GSH_df_pgls %>% 
  filter(PrimaryHabitat == 'Pelagic')

pelagic_spp_range <- c(min(as.numeric(pelagic_spp$Log10MeanGSH_centered)), max(as.numeric(pelagic_spp$Log10MeanGSH_centered)), min(pelagic_spp$Log10MaxSize_centered), max(pelagic_spp$Log10MaxSize_centered))

pelagic_ystart = pelagic_spp_range[1]*fit11_summary[2,1] + pelagic_spp_range[3]*fit11_summary[3,1] + fit11_summary[6,1]*pelagic_spp_range[1]*pelagic_spp_range[3] + fit11_summary[1,1]
  
pelagic_yend = pelagic_spp_range[2]*fit11_summary[2,1] + pelagic_spp_range[4]*fit11_summary[3,1] + fit11_summary[6,1]*pelagic_spp_range[2]*pelagic_spp_range[4] + fit11_summary[1,1]

PPC_plot1 <- PPC_plot1 + geom_segment(x = pelagic_spp_range[1], xend = pelagic_spp_range[2], y = pelagic_ystart, yend = pelagic_yend, color = 'blue')
PPC_plot1

ggsave(here('./Data/Output/PPC_plot1.png'), PPC_plot1, device = 'png', height = 6, width = 8, units = 'in')

```

```{r}
Prez_plot <- GSH_df_pgls %>% 
  data_grid(Log10CFAR_centered = seq_range(Log10CFAR_centered, 100), Binomial, Log10MaxSize_centered, Log10DepthMedian_centered) %>% 
  add_epred_draws(brms_9, ndraws = 10) %>% 
  ggplot(aes(y = Log10MeanGSH_centered, x = Log10CFAR_centered, color = Log10DepthMedian_centered), fill = Log10DepthMedian_centered) +
  stat_lineribbon(aes(y = .prediction), .width = c(.95, .80, .50), alpha = .25)+
  geom_point(data = GSH_df_pgls)+
  scale_fill_brewer(palette = 'Greys')+
  scale_colour_brewer(palette = 'Set2')
```



```{r}
ppd_dens_overlay(ypred = yrep[1:100, ])
```


```{r}
PPC_plot2 <- ppc_dens_overlay(y = GSH_df_pgls$Log10CFAR_centered, yrep = yrep[1:50, ], alpha = 0.25) +
  geom_vline(xintercept = mean(y), color = "#023858") +
  theme_transparent()

ggsave(here('./Data/Output/PPC_plot2.png'), PPC_plot2, device = 'png', height = 6, width = 8, units = 'in')

G <- GSH_df_pgls$PrimaryHabitat

PPC_plot3 <- ppc_dens_overlay_grouped(y = GSH_df_pgls$Log10CFAR, yrep = yrep[1:50, ], alpha = 0.25, group = G ) +
  theme_transparent()

ggsave(here('./Data/Output/PPC_plot3.png'), PPC_plot3, device = 'png', height = 6, width = 8, units = 'in')

PPC_plot4 <- ppc_stat_grouped(y = GSH_df_pgls$Log10CFAR, yrep = yrep, group = G, stat = 'mean') +
  theme_transparent()

ggsave(here('./Data/Output/PPC_plot4.png'), PPC_plot4, device = 'png', height = 6, width = 12, units = 'in')

```

```{r}
ppd_intervals(ypred = yrep, prob = 0.5, prob_outer = 0.95, x = as.numeric(GSH_df_pgls$Log10MeanGSH_centered))+
  labs(
    x = "Log10 Mean GSH",
    y = "Log10 CFAR",
    title = "95% posterior predictive intervals \nvs observed CFAR",
    subtitle = "by mean GSH (proportion total length)"
  ) 
```


```{r}
loo11 <- loo(SizeHabitatModel, save_psis = TRUE, cores = 4)

y <- GSH_df_pgls$Log10CFAR
yrep <- posterior_predict(SizeHabitatModel)
```

```{r}
psis11 <- loo11$psis_object
lw <- weights(psis11)
```

```{r}
color_scheme_set('purple')
ppc_loo_pit_overlay(y, yrep, lw = lw)
```

```{r}
ppc_loo_pit_qq(y, yrep, lw = lw, compare = 'normal')
```
```{r}
keep_obs <- c(1:100)

ppc_loo <- ppc_loo_intervals(y, yrep, psis_object = psis11, subset = keep_obs, order = 'median', prob = 0.95)

ggsave(here('./Data/Output/PPC_LOO_plot1.pdf'), ppc_loo, device = 'pdf', height = 6, width = 8, units = 'in')
```


```{r}
set.seed(11)

grid = data.frame(GSH_df_pgls)
  
means = grid %>%
  add_epred_draws(brms_9)

preds = grid %>%
  add_predicted_draws(brms_9)

ppc_habitat <- GSH_df_pgls %>%
  ggplot(aes(x = Log10MeanGSH_centered)) +
  stat_halfeye(aes(x = .epred), scale = 0.6, position = position_nudge(y = 0.175), data = means) +
  stat_interval(aes(x = .prediction), data = preds) +
  geom_point(data = GSH_df_pgls) +
  scale_color_brewer() +
  theme_bw()

ggsave(here('./Data/Output/PPC_Habitats_v1.png'), ppc_habitat, device = 'png', height = 6, width = 10, units = 'in')


ppc_habitat
```

```{r}
post_11 <- posterior_samples(brms_11)

post_11 %>% 
  ggplot(aes(x = b_Intercept, y = 0)) +
  stat_halfeye() +
  scale_y_continuous(NULL, breaks = NULL)


```

###THIS ONE
```{r}


p1 <- conditional_effects(brms_4, effects = "LogCFAR_centered:LogDepthMedian_centered",
                          int_conditions = list(Log10DepthMedian_centered = -1:1), prob = 0) 


sh.line.int <- p1[[1]]$estimate__[151] - p1[[1]]$estimate__[152] 
sh.line.int
  
dp.line.int <- p1[[1]]$estimate__[153] - p1[[1]]$estimate__[152] 
dp.line.int

size.labels <- c(-2, 0, 2, 4)
depth.labels <- rep(NA,4)

size.func <- function(x){
  exp((sd(GSH_df_full$LogMaxSize, na.rm = T)*x) + mean(GSH_df_full$LogMaxSize, na.rm = T))
}


size.labels <- size.func(size.labels)

for(i in -2:1){
  depth.labels[i +3] <- exp((sd(GSH_df_full$LogDepthMedian, na.rm = T)*i) + mean(GSH_df_full$LogDepthMedian, na.rm = T))
}

depth.labels <- round(depth.labels)
size.labels <- round(size.labels)

plot_11 <- ggplot(aes(x = LogCFAR_centered, y = LogMeanGSH_centered,  colour = LogDepthMedian_centered), data = GSH_df_full) + geom_point(alpha = 0.5, aes(size = LogMaxSize_centered)) +
  scale_size(guide = "legend", breaks = c(-2, 0, 2, 4), labels = size.labels, name = "Maximum Size (cm)") +
  scale_color_gradient(low = '#D1D5FF', high = '#070469', name = "Median Depth (m)", breaks = c(-2, -1, 0, 1), labels = depth.labels)+
  theme_bw()+
       ylab("Log10 GSH (proportion of TL)")+
       xlab("Log10 CFAR") +
  guides(color = guide_colourbar(reverse = TRUE))
  

#coastal
  for (i in 1:500) {
 plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4, summary = F)[i,1], slope = fixef(brms_4, summary = F)[i,2], color = adjustcolor("#1b9e77", alpha = 0.05), lty = 1) 
} 



#coastal
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1], slope = fixef(brms_4)[2,1], color = '#3343FF', size = 1.5)
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1] + sh.line.int, slope = fixef(brms_4)[2,1], color = '#7570b3', size = 1.5)
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1] + dp.line.int, slope = fixef(brms_4)[2,1], color = '#070469', size = 1.5) 


x.ticks <- rep(NA, 5)
for(i in -2:2){
x.ticks[i+3] <- exp((sd(GSH_df_full$LogCFAR)*i) + mean(GSH_df_full$LogCFAR))
}

y.ticks <- rep(NA, 5)
for(i in -2:2){
  y.ticks[i+3] <- (exp((sd(GSH_df_full$LogMeanGSH)*i) + mean(GSH_df_full$LogMeanGSH)) * 100)
}

x.ticks <- round(x.ticks,2)
y.ticks <- round(y.ticks,2)

plot_11 <- plot_11 +
  scale_x_continuous(name = "Activity level (CFAR)", breaks = c(-2,-1,0,1,2), labels = as.character(x.ticks)) +
  scale_y_continuous(name = "Mean GSH (percent TL)", breaks = c(-2,-1,0,1,2), labels = y.ticks)

plot_11 <- plot_11 + annotation_logticks()

img1 <- readPNG(here("Data","Input","Mako-281 (1).png"))
g1 <- rasterGrob(img1, interpolate = TRUE)

img2 <- readPNG(here("Data","Input","Apristurus-74.png"))
g2 <- rasterGrob(img2, interpolate = TRUE)

plot_11 <- plot_11 + geom_segment(x = 2.64, xend = (2.64-0.25),
                       y = 2.8 , yend = (2.8-0.25), size = 1.5, colour = 'grey10')

plot_11 <- plot_11 + geom_segment(x = -1.63, xend = (-1.63-0.5),
                       y = -0.88 , yend = (-2), size = 1.5, colour = 'grey10')

plot_11 <- plot_11 + annotation_custom(g1, xmin = 1.5, xmax = 2.64 , ymin = 1.5, ymax = 2.55) + annotation_custom(g2, xmin =-2.5 , xmax = (-1.5) , ymin = -2.94 , ymax = -1.55 )

ggsave(here('./Data/Output/Model4_plot.png'), plot_11, height = 15, width = 22, units = 'cm')

```




###THIS ONE pt. 2
```{r}


p1 <- conditional_effects(brms_4, effects = "LogCFAR_centered:LogDepthMedian_centered",
                          int_conditions = list(Log10DepthMedian_centered = -1:1), prob = 0.87) 


sh.line.int <- p1[[1]]$estimate__[151] - p1[[1]]$estimate__[152] 
sh.line.int
  
dp.line.int <- p1[[1]]$estimate__[153] - p1[[1]]$estimate__[152] 
dp.line.int

size.labels <- c(-2, 0, 2, 4)
depth.labels <- rep(NA,4)

size.func <- function(x){
  exp((sd(GSH_df_full$LogMaxSize, na.rm = T)*x) + mean(GSH_df_full$LogMaxSize, na.rm = T))
}


size.labels <- size.func(size.labels)

for(i in -2:1){
  depth.labels[i +3] <- exp((sd(GSH_df_full$LogDepthMedian, na.rm = T)*i) + mean(GSH_df_full$LogDepthMedian, na.rm = T))
}

depth.labels <- round(depth.labels, 2)
size.labels <- round(size.labels,2)

plot_test <- ggplot(aes(x = LogCFAR_centered, y = LogMeanGSH_centered,  colour = LogDepthMedian_centered), data = GSH_df_full) + geom_point(alpha = 0.5, aes(size = LogMaxSize_centered)) +
  scale_size(guide = "legend", breaks = c(-2, 0, 2, 4), labels = size.labels, name = "Max Size (cm)") +
  scale_color_gradient(low = '#D1D5FF', high = '#070469', name = "Median Depth (m)", breaks = c(-2, -1, 0, 1), labels = depth.labels)+
  theme_bw()+
       ylab("Log10 GSH (proportion of TL)")+
       xlab("Log10 CFAR") +
  guides(color = guide_colourbar(reverse = TRUE))
  

#coastal
  for (i in 1:500) {
 plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4, summary = F)[i,1], slope = fixef(brms_4, summary = F)[i,2], color = adjustcolor("#1b9e77", alpha = 0.05), lty = 1) 
} 



#coastal
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1], slope = fixef(brms_4)[2,1], color = '#3343FF', size = 1.5)
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1] + sh.line.int, slope = fixef(brms_4)[2,1], color = '#7570b3', size = 1.5)
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1] + dp.line.int, slope = fixef(brms_4)[2,1], color = '#070469', size = 1.5) 


x.ticks <- rep(NA, 5)
for(i in -2:2){
x.ticks[i+3] <- exp((sd(GSH_df_full$LogCFAR)*i) + mean(GSH_df_full$LogCFAR))
}

y.ticks <- rep(NA, 5)
for(i in -2:2){
  y.ticks[i+3] <- (exp((sd(GSH_df_full$LogMeanGSH)*i) + mean(GSH_df_full$LogMeanGSH)) * 100)
}

x.ticks <- round(x.ticks,2)
y.ticks <- round(y.ticks,2)

plot_11 <- plot_11 +
  scale_x_continuous(name = "Activity level (CFAR)", breaks = c(-2,-1,0,1,2), labels = as.character(x.ticks)) +
  scale_y_continuous(name = "Mean GSH (percent TL)", breaks = c(-2,-1,0,1,2), labels = y.ticks)

plot_11 <- plot_11 + annotation_logticks()

ggsave(here('./Data/Output/Model4_plot.png'), plot_11, height = 20, width = 30, units = 'cm')

```



```{r}
p2 <- plot_11 + p2

p2 <- plot(p1, points = T, plot = F)[[1]]  +
  scale_colour_manual(values = c('#D1D5FF', "#7570b3", "#3343FF")) +
  scale_fill_manual(values = c('#D1D5FF', "#7570b3", "#3343FF")) +
  theme_bw() + theme(legend.position = 'none')

p2 <- p2 + geom_abline(intercept = fixef(brms_4)[1,1], slope = fixef(brms_4)[2,1], color = '#1b9e77', size = 1.5)

p2

plot_11 <- ggplot(aes(x = Log10CFAR_centered, y = Log10MeanGSH_centered,  color = Log10DepthMedian_centered), data = GSH_df_pgls) 
  

#coastal
  for (i in 1:500) {
 plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4, summary = F)[i,1], slope = fixef(brms_4, summary = F)[i,2], color = adjustcolor("#1b9e77", alpha = 0.05), lty = 1) 
} 


plot_11 <- plot_11 +
  geom_abline(intercept = fixef(brms_4, summary = F)[i,1], slope = fixef(brms_4, summary = F)[i,2], color = adjustcolor("#1b9e77", alpha = 0.05), lty = 1)


#coastal
plot_11 <- plot_11 + geom_abline(intercept = fixef(brms_4)[1,1], slope = fixef(brms_4)[2,1], color = '#1b9e77', size = 1.5)


plot_11b <- plot_11 + geom_point(alpha = 0.5, aes(size = Log10MaxSize_centered)) +
  scale_color_gradient(low = '#D1D5FF', high = '#3343FF')+
  theme_bw()+
  ggtitle(paste("Correlation=", cor(GSH_df_pgls$Log10CFAR, GSH_df_pgls$Log10MeanGSH_centered)))+
       ylab("Log10 GSH (proportion of TL)")+
       xlab("Log10 CFAR") 
  


plot_11b 

ggsave(here('./Data/Output/Model9_plot.png'), plot_11b, height = 20, width = 30, units = 'cm')




```

```{r}
brms_x_prior <- get_prior(LogMeanGSH_centered ~ LogCFAR_centered + LogMaxSize_centered + LogDepthMedian_centered*LogCFAR_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_full,
                    family = gaussian(),
                    data2 = list(B = B))


brms_x <- brm(LogMeanGSH_centered ~ LogCFAR_centered + LogMaxSize_centered + LogDepthMedian_centered*LogCFAR_centered + (1|gr(Binomial, cov = B)),
                    data = GSH_df_full,
                    family = gaussian(),
                    data2 = list(B = B),
                    prior = brms_x_prior,
                    chains = 4, cores = 4,
                    warmup = 1000, iter = 5000)



plot_15 <- ggplot(aes(x = LogCFAR_centered, y = LogMeanGSH_centered,  color = LogDepthMedian_centered), data = GSH_df_full) 
  

#coastal
  for (i in 1:500) {
 plot_15 <- plot_15 + geom_abline(intercept = fixef(brms_x, summary = F)[i,1], slope = fixef(brms_x, summary = F)[i,2], color = adjustcolor("#1b9e77", alpha = 0.05), lty = 1) 
} 





#coastal
plot_15 <- plot_15 + 
  geom_abline(intercept = (fixef(brms_x)[1,1] - fixef(brms_x)[5,1]), slope = fixef(brms_x)[2,1], color = '#D1D5FF', size = 1.5) +
  geom_abline(intercept = fixef(brms_x)[1,1], slope = fixef(brms_x)[2,1], color = '#7570b3', size = 1.5) +
  geom_abline(intercept = (fixef(brms_x)[1,1] + fixef(brms_x)[5,1]), slope = fixef(brms_x)[2,1], color = '#3343FF', size = 1.5)
  


plot_15b <- plot_15 + geom_point(alpha = 0.5, aes(size = LogMaxSize_centered)) +
  scale_color_gradient(low = 'grey90', high = '#3343FF')+
  theme_bw()+
  #ggtitle(paste("Correlation=", cor(GSH_df_full$Log10CFAR_centered, GSH_df_full$LogMeanGSH_centered)))+
       ylab("Log10 GSH (proportion of TL)")+
       xlab("Log10 CFAR") 
  


plot_15b 

```





```{r}
library(insight)
library(bayestestR)
library(patchwork)
# S3 method for brmsfit
brms_4_post <- get_parameters(
  brms_4,
  effects = "fixed",
  component = "all",
  parameters = NULL,
  summary = FALSE,
  centrality = "mean"
)

head(brms_4_post)

brms_4_CI <- ci(brms_4, method = "HDI", component = 'all')

brms_4_CI$CI_low[1]


out <- estimate_density(brms_4_post, extend = T, select = 'b_Intercept')

#intercept 
out_IC <- estimate_density(brms_4_post, extend = T, select = 'b_Intercept')

I_C <- ggplot(out_IC, aes(x = x, y = y)) +
  geom_segment(x = brms_4_CI$CI_low[1], xend = brms_4_CI$CI_high[1], y = 1.25, yend = 1.25, color = 'black', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_4_post$b_Intercept), y = 1.25, size = 2,  color = 'black') +
  geom_vline(xintercept = 0, lty = 2) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  annotate("text", x = 1.15, y = 1, label = "Intercept") +
    annotate("text", x = -1, y = 1.5, label = "d)") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

I_C


#slope - CFAR
out_SG <- estimate_density(brms_4_post, extend = T, select = 'b_LogCFAR_centered')

S_G <- ggplot(out_SG, aes(x = x, y = y)) +
  geom_segment(x = brms_4_CI$CI_low[2], xend = brms_4_CI$CI_high[2], y = 1.25, yend = 1.25, color = 'black', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_4_post$b_LogCFAR_centered), y = 1.25,  color = 'black', size = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  annotate("text", x = 1.15, y = 1, label = "Activity") +
    annotate("text", x = -1, y = 1.5, label = "a)") +
   annotate("text", x = 0.65, y = 1.25, label = "Ecological lifestyle model", size = 3) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_G
#slope - Size
out_SS <- estimate_density(brms_4_post, extend = T, select = 'b_LogMaxSize_centered')

S_S <- ggplot(out_SS, aes(x = x, y = y)) +
  geom_segment(x = brms_4_CI$CI_low[3], xend = brms_4_CI$CI_high[3], y = 1.25, yend = 1.25, color = 'black', size = 0.5, alpha = 0.3) +
  geom_point(x = mean(brms_4_post$b_LogMaxSize_centered), y = 1.25, color = 'black', size = 2) +
    geom_vline(xintercept = 0, lty = 2) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  annotate("text", x = 1.15, y = 1, label = "Maximum size") +
    annotate("text", x = -1, y = 1.5, label = "b)") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_S


LEG.df <- data.frame(x = c(rep(-0.75,4)), y = c(0.425, 0.675, 0.925, 1.175), size = 2, shape = c(23, 15, 17, 16), color = c('grey60','grey60','grey60', 'black'))


LEG <- ggplot(LEG.df, aes(x = x, y = y)) +
  geom_point(size = 2, shape = LEG.df$shape, color = LEG.df$color, fill = 'grey60')+
  xlim(-1,1.25)+
  ylim(0,2)+
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))


LEG <- LEG +
  annotate("text", x = -0.5, y = 1.5, label = "Model", size = 4) +
  annotate("text", x = -0.5, y = 1.175, label = "Ecological lifestyle", size = 3) +
  annotate("text", x = -0.5, y = 0.925, label = "Activity", size = 3) +
  annotate("text", x = -0.5, y = 0.675, label = "Max Size", size = 3) +
  annotate("text", x = -0.5, y = 0.425, label = "Depth", size = 3) +
  geom_segment(x = -0.85, xend = -0.25, y = 1.65, yend = 1.65) +
  geom_segment(x = -0.85, xend = -0.25, y = 0.25, yend = 0.25) +
  geom_segment(x = -0.85, xend = -0.85, y = 0.25, yend = 1.65) +
  geom_segment(x = -0.25, xend = -0.25, y = 1.65, yend = 0.25)

LEG

#slope - Depth
out_SD <- estimate_density(brms_4_post, extend = T, select = 'b_LogDepthMedian_centered')

S_D <- ggplot(out_SD, aes(x = x, y = y)) +
 geom_segment(x = brms_4_CI$CI_low[4], xend = brms_4_CI$CI_high[4], y = 1.25, yend = 1.25, color = 'black', size = 0.5, alpha = 0.3) +
  geom_point(x = mean(brms_4_post$b_LogDepthMedian_centered), y = 1.25, color = 'black', size = 2) +
    geom_vline(xintercept = 0, lty = 2) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  annotate("text", x = 1.15, y = 1, label = "Median Depth") +
  annotate("text", x = -1, y = 1.75, label = "c)") +
 theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_D


#sigma
out_sigma <- estimate_density(brms_4_post, extend = T, select = 'sigma')


SIG <- ggplot(out_sigma, aes(x = x, y = y)) +
  geom_segment(x = brms_4_CI$CI_low[5], xend = brms_4_CI$CI_high[5], y = 1.25, yend = 1.25, color = 'black', size = 0.5, alpha = 0.3) +
  geom_point(x = mean(brms_4_post$sigma), y = 1.25, color = 'black', size = 2) +
    geom_vline(xintercept = 0, lty = 2) +
  scale_x_continuous(name = "Coefficient estimates", limits = c(-1, 1.25), breaks = c(-1, 0, 1)) +
  ylim(0,2) +
  annotate("text", x = 1.15, y = 1, label = "Sigma") +
  annotate("text", x = -1, y = 1.5, label = "e)") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.line.x = element_line(size = 1, color = 'black', linetype = 'solid'),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))


SIG

```



```{r}
# S3 method for brmsfit
brms_1_post <- get_parameters(
  brms_1,
  effects = "fixed",
  component = "all",
  parameters = NULL,
  summary = FALSE,
  centrality = "mean"
)

head(brms_1_post)

brms_1_CI <- ci(brms_1, method = "HDI", component = 'all')

brms_1_CI$CI_low[1]



#intercept 
out_IC1 <- estimate_density(brms_1_post, extend = T, select = 'b_Intercept')

I_C1 <- ggplot(out_IC1, aes(x = x, y = y)) +
  geom_segment(x = brms_1_CI$CI_low[1], xend = brms_1_CI$CI_high[1], y = 1, yend = 1, color = 'grey60', size = 0.5, alpha = 0.5)+
  geom_point(x = mean(brms_1_post$b_Intercept), y = 1, color = 'grey60', size = 2, shape = 17, alpha = 0.1) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

I_C1


#slope - CFAR
out_SG1 <- estimate_density(brms_1_post, extend = T, select = 'b_LogCFAR_centered')

S_G1 <- ggplot(out_SG1, aes(x = x, y = y)) +
  geom_segment(x = brms_1_CI$CI_low[2], xend = brms_1_CI$CI_high[2], y = 1, yend = 1, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_1_post$b_LogCFAR_centered), y = 1, color = 'grey60', size = 2, shape = 17) +
  annotate("text", x = 0.65, y = 1, label = "Activity only model", size = 3, color = 'grey60') +

  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_G1

#sigma
out_sigma1 <- estimate_density(brms_1_post, extend = T, select = 'sigma')


SIG1 <- ggplot(out_sigma1, aes(x = x, y = y)) +
  geom_segment(x = brms_1_CI$CI_low[3], xend = brms_1_CI$CI_high[3], y = 1, yend = 1, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_1_post$sigma), y = 1, color = 'grey60', size = 2, shape = 17) +
  scale_x_continuous(name = "Coefficient estimates", limits = c(-1, 1.25), breaks = c(-1, 0, 1)) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))


SIG1
```



```{r}
# S3 method for brmsfit
brms_2_post <- get_parameters(
  brms_2,
  effects = "fixed",
  component = "all",
  parameters = NULL,
  summary = FALSE,
  centrality = "mean"
)

head(brms_2_post)

brms_2_CI <- ci(brms_2, method = "HDI", component = 'all')

brms_2_CI$CI_low[1]


out <- estimate_density(brms_2_post, extend = T, select = 'b_Intercept')

#intercept 
out_IC2 <- estimate_density(brms_2_post, extend = T, select = 'b_Intercept')

I_C2 <- ggplot(out_IC2, aes(x = x, y = y)) +
  geom_segment(x = brms_2_CI$CI_low[1], xend = brms_2_CI$CI_high[1], y = 0.8, yend = 0.8, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_2_post$b_Intercept), y = 0.8, color = 'grey60', size = 2, shape = 15) +
  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

I_C2



#slope - Size
out_SS2 <- estimate_density(brms_2_post, extend = T, select = 'b_LogMaxSize_centered')

S_S2 <- ggplot(out_SS2, aes(x = x, y = y)) +
  geom_segment(x = brms_2_CI$CI_low[2], xend = brms_2_CI$CI_high[2], y = 1, yend = 1, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_2_post$b_LogMaxSize_centered), y = 1,  color = 'grey60', size = 2, shape = 15) +
  annotate("text", x = 0.65, y = 1, label = "Maximum size only model", size = 3, color = 'grey60') +
  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_S2



#sigma
out_sigma2 <- estimate_density(brms_2_post, extend = T, select = 'sigma')


SIG2 <- ggplot(out_sigma2, aes(x = x, y = y)) +
  geom_segment(x = brms_2_CI$CI_low[3], xend = brms_2_CI$CI_high[3], y = 0.8, yend = 0.8, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_2_post$sigma), y = 0.8, color = 'grey60', size = 2, shape = 15) +
  scale_x_continuous(name = "Coefficient estimates", limits = c(-1, 1.25), breaks = c(-1, 0, 1)) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))


SIG2
```




```{r}
# S3 method for brmsfit
brms_3_post <- get_parameters(
  brms_3,
  effects = "fixed",
  component = "all",
  parameters = NULL,
  summary = FALSE,
  centrality = "mean"
)

head(brms_3_post)

brms_3_CI <- ci(brms_3, method = "HDI", component = 'all')

brms_3_CI$CI_low[1]


out <- estimate_density(brms_3_post, extend = T, select = 'b_Intercept')

#intercept 
out_IC3 <- estimate_density(brms_3_post, extend = T, select = 'b_Intercept')

I_C3 <- ggplot(out_IC3, aes(x = x, y = y)) +
  geom_segment(x = brms_3_CI$CI_low[1], xend = brms_3_CI$CI_high[1], y = 0.6, yend = 0.6, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_3_post$b_Intercept), y = 0.6, color = 'grey60', size = 2, shape = 23, fill = 'grey60') +
  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

I_C3



#slope - Depth
out_SD3 <- estimate_density(brms_3_post, extend = T, select = 'b_LogDepthMedian_centered')

S_D3 <- ggplot(out_SD3, aes(x = x, y = y)) +
  geom_segment(x = brms_3_CI$CI_low[2], xend = brms_3_CI$CI_high[2], y = 1, yend = 1, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_3_post$b_LogDepthMedian_centered), y = 1, color = 'grey60', size = 2, shape = 23, fill = 'grey60') +
  annotate("text", x = -0.55, y = 1, label = "Median depth only model", size = 3, color = 'grey60') +
  xlim(-1, 1.25) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))

S_D3



#sigma
out_sigma3 <- estimate_density(brms_3_post, extend = T, select = 'sigma')


SIG3 <- ggplot(out_sigma3, aes(x = x, y = y)) +
  geom_segment(x = brms_3_CI$CI_low[3], y = 0.6, xend = brms_3_CI$CI_high[3], yend = 0.6, color = 'grey60', size = 0.5, alpha = 0.3)+
  geom_point(x = mean(brms_3_post$sigma), y = 0.6, color = 'grey60', size = 2, shape = 23, fill = 'grey60') +
  scale_x_continuous(name = "Coefficient estimates", limits = c(-1, 1.25), breaks = c(-1, 0, 1)) +
  ylim(0,2) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA))


SIG3
```







### layout


```{r}


layout <- c(area(t=1,b=2,r=1,l=1), #brms 4 CFAR
            area(t=1, b=2.1, r=1,l=1), #brms 1 CFAR
            area(t=2,b=3,r=1,l=1), #brms 4 size
            area(t=2, b=3.1, r=1,l=1), #brms 2 size
            area(t=3,b=4,r=1,l=1), #brms 4 depth
            area(t=3, b=4.1,r=1,l=1), #brms 3 depth
            area(t=4,b=5,r=1,l=1), #brms 4 Int
            area(t=4,b=5.1,r=1,l=1), #brms 1 Int
            area(t=4,b=5.2,r=1,l=1), #brms 2 Int
            area(t=4,b=5.3,r=1,l=1), #brms 3 Int
            area(t=5,b=6,r=1,l=1), #brms 4 sigma
            area(t=5, b=6.1,r=1,l=1), #brms 1 sigma
            area(t=5, b=6.2,r=1,l=1), #brms 2 sigma
            area(t=5, b=6.3,r=1,l=1) #brms 3 sigma
            ) 

panel_plot <- S_G + S_G1 + S_S + S_S2 + S_D + S_D3 + I_C + I_C1 + I_C2 + I_C3 + SIG + SIG1 + SIG2 + SIG3 + plot_layout(design = layout)

panel_plot2 <- plot_11b + panel_plot + plot_layout(widths = c(2,1)) + plot_annotation(tag_levels = 'a')

panel_plot2

ggsave(here('./Data/Output/Fig1_Draft.png'), panel_plot2, height = 20, width = 35, units = 'cm')

ggsave(here('./Data/Output/panel_plot_v2.png'), panel_plot, height = 10, width = 20, units = 'cm')


```


```{r}
boxplot <- ggplot(GSH_df_pgls, aes(x = PrimaryHabitat, y = Log10CFAR_centered), colour = PrimaryHabitat)+
  geom_boxplot(aes(fill = PrimaryHabitat), alpha = 0.3) +
  geom_point(aes(colour = PrimaryHabitat)) +
  scale_color_manual(values = c("Coastal" = "#d95f02",
                                "Deepwater" = "#7570b3",
                                "Pelagic" = "#1b9e77")) +
  scale_fill_manual(values = c("Coastal" = "#d95f02",
                                "Deepwater" = "#7570b3",
                                "Pelagic" = "#1b9e77")) +
  theme_light()
  

boxplot

ggsave(here('./Data/Output/boxplot_habitat.png'), boxplot, height = 20, width = 30, units = 'cm')

```


# Coef plot

```{r}
bayesplot::mcmc_areas(brms_4, pars = c('b_Intercept','b_Log10CFAR_centered','b_Log10MaxSize_centered', 'b_Log10DepthMedian_centered',
                                       'sigma'), prob = 0.8)
```

```{r}
summarise_draws(tidy_draws(brms_4))
```

```{r}
brms_4 %>% 
  gather_rvars(b_Intercept, b_Log10CFAR_centered, b_Log10MaxSize_centered, b_Log10DepthMedian_centered, sigma) %>% 
  ggplot(aes(y = .variable, xdist = .value)) +
  stat_halfeye() +
  theme_bw()
```

```{r}
GSH_df_pgls %>% 
  data_grid(Log10CFAR_centered = seq_range(Log10CFAR_centered, n = 10), Binomial = sample(Binomial, 10),
            Log10DepthMedian_centered = seq_range(Log10DepthMedian_centered, n = 10),
            Log10MaxSize_centered = seq_range(Log10MaxSize_centered, n = 10)) %>% 
  add_epred_rvars(brms_4) %>% 
  ggplot(aes(x = Log10CFAR_centered, color = Log10DepthMedian_centered)) +
  stat_lineribbon(aes(ydist = .epred)) +
  geom_point(aes(y = Log10MeanGSH_centered), data = GSH_df_pgls) +
  scale_color_gradient(low = 'white', high = '#7570b3')
```


```{r}

pp1 <- pp_check(brms_1, ndraws = 100) + ggtitle("Activity")
pp2 <- pp_check(brms_2, ndraws = 100) + ggtitle("Size")
pp3 <- pp_check(brms_3, ndraws = 100) + ggtitle("Depth")
pp4 <- pp_check(brms_4, ndraws = 100) + ggtitle("EcoLife")

pp.plot <- (pp1 + pp2) / (pp3 + pp4)

pp.plot

ggsave(here('./Data/Output/ppC_plot.png'), pp.plot, height = 20, width = 20, units = 'cm')


```

### Supp fig size ~ depth
```{r}
Size.depth <- ggplot(data = GSH_df_full, aes(x = LogDepthMedian, y = LogMaxSize)) +
  geom_point() +
  geom_smooth(method = 'lm', formula = 'y ~ x')

Size.depth
```

```{r}
ggsave(here('./Data/Output/Supp_size_depth.png'), Size.depth, device = 'png', height = 6, width = 8, units = 'in')
```



### Just messing around
```{r}

two_points <- GSH_df_full %>% 
  filter(Binomial %in% c("Isurus_paucus","Apristurus_herklotsi"))

two_points[1,c("LogCFAR_centered","LogMeanGSH_centered")]

plot_11 <- ggplot(aes(x = LogCFAR_centered, y = LogMeanGSH_centered,  colour = LogDepthMedian_centered), data = two_points) + geom_point()
```

